experiment:
  attacks:
  - ${attack}

attack: null

# ====

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      partitioner: iid
      +datasets: nfv2/sampled/nb15
      batch_size: 512
      +epochs: 100/10x10
      +distribution: 9-1,7-3,5-5,3-7
      +target: untargeted
      +scenario: continuous-10,continuous-30,continuous-60,continuous-70,continuous-80,continuous-90,continuous-95,continuous-99,continuous-100
      seed: 1138,421,1313,5555,6567,327,2187,1977,501,3263827