experiment:
  attacks:
  - ${attack}
  partitioner: 
    attacker_target: ${experiment.attacks[0].target}
    n_attackers: ${experiment.pools[0].n_malicious}
  strategy:
    _target_: assessment.similarity.module.SaveFedAvg

attack: null

# ====

hydra:
  searchpath:
    - pkg://eiffel.conf