

experiment:
  # Experiment confirguration

  hardware:
    # Per-client ressources. These fields are passed as-is to Flower, which gives them
    # then to Ray. See: https://flower.dev/docs/framework/how-to-run-simulations.html.
    num_gpu: 0
    num_cpu: 0

  distribution:
    # Client pools.
    - dataset: ${datasets.${data}}
      clients:
        benign: 7
        malicious: 3
      target: [ Reconnaissance ]
      target_ref: ${.target}
      attack: ${attacks.profile}
        # profile: ${attack.poisoning.profile}
        # type: ${attack.poisoning.type}

  attack:
    type: str
    profile: str

defaults:
  - _self_

  - attacks/type: targeted
  - attacks/profile: decrement